### ISSUE TITLE
v0.3 breaks frontend with multiple switches

### ISSUE THREAD

**Issue by smnino** [twrecked/hass-momentary#1] opened 2019-09-07 03:52 UTC
With the latest v0.3, when multiple switches are setup, hass frontend doesn't load and no errors are present in the log. Rolling back to v.2, all works as expected.

I am running hasbian docker v 97.2

**Comment by twrecked** [comment] 2019-09-07 12:05
Do you mind sending the switch configs? It's working for me and the only changes were fixing a default config value.

Thanks

**Comment by smnino** [comment] 2019-09-07 14:43
I haven’t used GitHub much so, excuse my ignorance. Do you want my entire switches.yaml file? If not, the configs for just the momentary switches are as follows:

- platform: momentary
  name: Resume Schedule
  on_for: 1
  allow_off: false

- platform: momentary
  name: Cancel Irrigation
  on_for: 1
  allow_off: false

**Comment by twrecked** [comment] 2019-09-07 15:40
That's great thanks. I'll take a look at the issue.

**Comment by smnino** [comment] 2019-09-07 15:42
Thank you for the code. Dunno why this has to be a 3rd part solution? Should be a button and part of the base system. Users have been asking for this forever….

**Comment by twrecked** [comment] 2019-09-07 15:47
I agree, I ended up writing it because it was missing...

I think the problem is because I fixed an issue with `on_for` in 0.3 - it wasn't setting a default correctly in 0.2. I'll try and reproduce the issue here but I have some errands to run so it might be later today.

One thing to try - if it's not too much trouble - is to upgrade to 0.3 and rename both devices and try starting again. I think some saved state maybe causing the issue.

**Comment by smnino** [comment] 2019-09-07 16:40
I think you’re right. I upgraded to v3 and renamed both switches. After a restart the frontend loaded with not problem. Thanks again!

**Comment by twrecked** [comment] 2019-09-09 00:30
Is it ok to close this one?

I tried to reproduce the issue by going from 0.2 -> 0.3 several times and never had the problem. But I have definitely seen bad configuration code hold the entire system up - I also maintain the Aarlo component and broke my own system the other night with such code - and 0.2 had bad configuration code which could have broke 0.3

You might find renaming the switches to their original name works now.

**Comment by twrecked** [comment] 2019-11-21 14:21
Closing. Was an upgrade issue.

**Closed by twrecked** 2019-11-21 14:21 UTC
